### ISSUE TITLE
Not showing up even after conflict deletion?

### ISSUE THREAD

**Issue by oliverban** [JaredTherriault/ComfyUI-JNodes#1]
The nodes in this one do not show up in comfyui after install. Tried manual and through Manager. Conflict files have been moved/deleted but still, nothing loads.

**Comment by JaredTherriault** [comment]
Ok, let's try to troubleshoot. First, what browser are you using on which OS? I've only really been developing on Brave/Manjaro so far so it's unknown how well this code plays with other environments.

Most browsers will open developer tools with ctrl/cmd + Shift + I. Try that and look for the console tab. Clear the console (it's a button that looks like a circle with a line through it on Brave), refresh the comfy page and copy in what you see in the console.

**Comment by JaredTherriault** [comment]
Also there is a chance the whole suite is failing to load due to some dependency errors. When you start up comfy and it shows you the IP address at the bottom of the console window, slightly above there is a list of custom nodes. Ensure that it doesn't say "IMPORT_FAILED" beside ComfyUI-JNodes.
