### ISSUE TITLE
Allow searching models by subfolder.

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#11]
I don't know how viable this is to implement, but I'll suggest it anyway.  I noticed that hover text on the button to drop a node for a lora onto the grid includes the full path, and file extension for the lora.  Would it be possible to put the same thing into the filename in the lora drawer, and allow searching by filename?

I use separate folders for SDXL, or SD1.5 based models, and while I like the lora drawer, I haven't been using it because there's no way filter it unless you know exactly which model you want.

**Comment by JaredTherriault** [comment]
Hey, thank you for reminding me. This is something I wanted to implement but kind of got lost in the shuffle for 1.0. It's in now. 

Ideally I'd like to implement something like the subdirectory selector in input and output contexts, but it would require a massive refactor of the models code and I just haven't had time. This will work around that, provided you know your lora folder structure.

Now you can keep your loras in separate folders and if you want to return just the items in the SDXL folder, type "SDXL/" (forward slash) into the lora search bar.

**Comment by Monty1836** [comment]
Thank you!  I had suspected there were deeper issues that were preventing you from implementing a selector like in the other contexts, it's why my request was only for the search.  Being able to select folders from a dropdown would be nice, but practically speaking, this gets the job done just fine.  The way your search works, is actually very versatile.  Again, thank you!  I'd really missed the lora selector from Auto1111 when I switched to ComfyUI, and thanks to you, there's finally a replacement.

**Comment by JaredTherriault** [comment]
> Thank you! I had suspected there were deeper issues that were preventing you from implementing a selector like in the other contexts, it's why my request was only for the search. Being able to select folders from a dropdown would be nice, but practically speaking, this gets the job done just fine. The way your search works, is actually very versatile. Again, thank you! I'd really missed the lora selector from Auto1111 when I switched to ComfyUI, and thanks to you, there's finally a replacement.

I know this is a late addition, just wanted to let you know that i was able to untangle some wires and this feature is now in! It starts loading no models - to get all models select /root, otherwise select individual folders.

**Comment by Monty1836** [comment]
Oh, very good to hear, thanks!
