### ISSUE TITLE
Images in drawer sometimes get cut off.

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#13]
![Untitled](https://github.com/user-attachments/assets/bce3ec6c-b71b-4b49-b333-85ff6a2bb332)
I'm not sure what the reasoning is behind it, but for some reason the edge next to the scroll bar gets cut off sometimes.

Hovering the cursor over the image also usually has an effect.  Either causing the image to be cut off in the first place, or fixing it if it already was.  Sometimes it doesn't do anything at all, and other times it will fix all of the images below the one you're currently hovering.

From what I can tell, it's related to the image's aspect ratio.  A 512x512 image won't cause the problem, and neither will a 256x512 image, but a 288x512 image will, and the 512x768 NoImage.png file you use when models are missing a preview does it as well.

**Comment by JaredTherriault** [comment]
Yeah, I knew about this weird thing. It has to do with the way images get cropped for lora and embedding covers, but i haven't found the solution yet and considered it to be very low-priority. Thank you for the report though, I hadn't made the connection between the issue and aspect ratio, so very good to know! I don't know when I will get to this issue, but again, way lower priority than most other issues and features.

**Comment by Monty1836** [comment]
It's definitely not an important issue, it's just a minor graphical error.  It's not just for the lora, and embedding covers though, I actually tested resolutions using the regular image feed.  It seems to effect everything in the image drawer.

**Comment by JaredTherriault** [comment]
I'm still not sure what the cause is here, but it seems to only affect Chromium-based browsers. I can't reproduce it on Firefox-based browsers. Can you let me know which browser you're using and if it is still present in both browsers for you?

**Comment by Monty1836** [comment]
Playing around with CSS a bit to try to find the cause, I did actually find a functional workaround.  Padding the right side by 6% pushes the drawer contents far enough to the left that the only thing that's cut off is the padding.  It's not really a solution, but it does make it less noticeable at the cost of some empty space in the image drawer.

```
.JNodes-image-drawer-list {
padding-right: 6%;
}
```

Interestingly "justify-items: end;" seems to actually fix the issue in the lora, and embedding contexts, but doesn't help when hovering over images in other contexts.  Justify only effects the position of elements on the page, so it's somehow related to the position of things in the grid.  If I had to guess, I'd say it doesn't help the other contexts because when you hover over images in those contexts, it adds a new element to the page, and inserts it into the grid, which changes the position of other elements internally.  I'm really not sure though, it's strange that changing the justify setting would have any effect on it at all.

**Comment by Monty1836** [comment]
Found it!

The scrollbar gutter is causing the problem.  Removing the both-edges setting fixes the issue completely.  It seems like Chromium doesn't like that setting.

This:
```
.JNodes-image-drawer-list {
scrollbar-gutter: stable both-edges;
}
```
Gets changed to:
```
.JNodes-image-drawer-list {
scrollbar-gutter: stable;
}
```

**Comment by JaredTherriault** [comment]
Yup, that works! Thanks for this, just pushed it with credit to you!

**Comment by Monty1836** [comment]
Glad to hear it, thanks for the update!
