### ISSUE TITLE
Collapsible Settings No Longer Needed

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#15]
ComfyUI has pushed an update which has added individual tabs for settings added by each extension.  That means by default, JNodes' tab is now a big empty box until you expand it.
![image](https://github.com/user-attachments/assets/6cafdaa8-c039-4814-b200-8c90e4413649)

**Comment by JaredTherriault** [comment]
Thanks, I have updated the settings code to play nicer with the new UI.
