### ISSUE TITLE
 Show Image Drawer Button Does Not Display in New UI...  Again!

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#20]
I noticed the button in the new UI to show the image drawer when it's hidden was rendering incorrectly.  Greyed out, but visible when the image drawer was open.  I decided to hide it to see if the button is just always visible now, which would be fine.  Hiding the drawer also hid the button in the new UI, but showed it in the old UI.  I then clicked the button to show the image drawer from legacy UI, and it did this!
![{D83C4974-F5D9-4944-AC14-F09BF8F96D71}](https://github.com/user-attachments/assets/72b05625-14b1-494e-b4df-763ccbf9d10a)

Enabling the new UI again with the image drawer in this broken state reveals that it's trying to dock some parts of the image drawer into the default ComfyUI sidebar.  Honestly, having the option dock the image drawer into the default sidebar in addition to working standalone seems great!  Docking into the default sidebar would be preferred way to use it if you could get the whole thing working in there, and add a toggle for people that like having them on opposite sides.
![{2B3BA95F-EB58-4C23-A800-EE5027ED163C}](https://github.com/user-attachments/assets/8be3b972-f735-4b39-98d4-a24a5e42c029)

**Comment by Monty1836** [comment]
Digging in a little further, it looks like the second image feed is the Pysssss image feed, which is enabled due to a conflict with ComfyUI's new built-in extensions menu.  Forwarding disabled extensions from your menu into the default ComfyUI one has fixed that, but docking into the default sidebar like that would still be great to have.

The button to show the image drawer in the new menu still doesn't appear though, so it must have been broken by recent changes.  Updating title to reflect this.

**Comment by JaredTherriault** [comment]
Hey Monty, thank you for the report. I have fixed this button issue here: https://github.com/JaredTherriault/ComfyUI-JNodes/commit/dadcc9648ba503785ba717f5405105af73eed16a

I like the idea of docking the drawer into the sidebar, but I don't want to spend the time on it until the new menu is finalized - Comfy still considers it experimental, and this is evidenced by the button I just fixed having been broken in the first place. Once the menu is forced or at least out of experimental stage, I will definitely look into the sidebar docking option. Please feel free to open a new feature request when the time comes!

**Comment by JaredTherriault** [comment]
> Actually, the new UI was made the default option on November 15th, so all new installs of ComfyUI will have it enabled unless the user changes the setting manually They've also removed the experimental tag from the option in the settings menu. They made an announcement about it on their github, which you can find here: [comfyanonymous/ComfyUI#5395](https://github.com/comfyanonymous/ComfyUI/issues/5395)
> 
> Regardless, thanks for the fix! It was a relatively minor issue, but still nice to see the bug squashed. I also appreciate the change so you can have both buttons without a refresh!

Hey so the sidebar tab is now implemented! Just change the anchor type from 'top-left' or whatever it is to 'sidebar'.

You can also have multiple drawer instances now instead of just the one, so you can mix and match sidebar tabs and floating frames if you so choose.

**Comment by Monty1836** [comment]
I like the multiple instances, I never realized how nice it would be to keep the image feed open in the sidebar at the same time as having the lora context floating alongside it.  Very good idea!  I noticed that if you have multiple of them in the sidebar at the same time, they look exactly the same.  Maybe change the icon, and title in the sidebar based on the current context selected?  That's really the only improvement I can think of.  Very nice feature, and very nice implementation.  Thanks!

**Comment by JaredTherriault** [comment]
> I like the multiple instances, I never realized how nice it would be to keep the image feed open in the sidebar at the same time as having the lora context floating alongside it. Very good idea! I noticed that if you have multiple of them in the sidebar at the same time, they look exactly the same. Maybe change the icon, and title in the sidebar based on the current context selected? That's really the only improvement I can think of. Very nice feature, and very nice implementation. Thanks!

Best I can do is tint each button and add the instance number. I can't change the tooltip after registering without unregistering and registering again, which will affect the order of the buttons and I don't want to do that. But differentiating the buttons was a great idea - it's in now!

**Comment by JaredTherriault** [comment]
Thanks for the heads up, I missed a "." between an instance and a function call. A Facepalm moment.

I'm not sure I love the idea of a sidebar button for floating drawers. I don't want to clutter up a limited space if I don't have to. I'd be open to having a single button that can act as a control space for floaters though. It would be a stretch goal however. This was already a four-day endeavour for the first draft.

**Comment by Monty1836** [comment]
Moving image drawers out of the sidebar looks like it works properly now.  Thanks for the fix!  There is still a minor issue of the image drawer appearing at the bottom of the screen until you select it in the sidebar the first time, or refresh the page.  Here's a picture of it, even if it's not much of a problem..

![Image](https://github.com/user-attachments/assets/9a6638d5-5e13-4902-8ee5-ac723e35bd41)

Not wanting to add buttons for floating drawers into the sidebar is fine, no worries!  Space concerns are perfectly reasonable.  The icons for the floating drawers still seem to be broken, and the buggy behaviour when you reload the page with one of them hidden is still present.  If you'd tried to fix that part, it doesn't seem to be resolved.

**Comment by Monty1836** [comment]
Oh, a little bit of extra testing.  All of the icons do show up once every feed has fully loaded, not just two.  It was just taking a while to load the lora drawer, and I didn't wait long enough to realize.  It is hiding all of the drawers if any of them are hidden when you reload the page, though.  That includes the drawer that's docked to the sidebar, though they don't actually hide in the sidebar anyway, it just spawns the button.
