### ISSUE TITLE
Feed images don't respect ComfyUI's output directory.

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#6]
![image](https://github.com/JaredTherriault/ComfyUI-JNodes/assets/143219756/ca42880e-1ceb-45d3-9096-0a8d16739862)
As you can see in the above screenshot, images in the feed don't seem to actually exist where the feed is looking for them.

From what I can tell, it looks like the reason is simple.  I'm using ComfyUI's "--output-directory" paramater to change the output directory, and it seems like the feed doesn't check with ComfyUI to make sure it's actually looking in the right folder for the output images.

**Comment by JaredTherriault** [comment]
Hey, thank you for the report. I've pushed an update that _may_ fix this, but I can't reproduce it myself so I'm not sure.

If this issue isn't resolved, can you please respond with your operating system, browser, and logs, both browser and python logs.

**Comment by Monty1836** [comment]
Looks to me like the fix is working perfectly.  Thanks for the help!
