### ISSUE TITLE
Settings don't save to comfy.settings.json

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#7]
It seems like all of the settings from this repo only save to browser data.  This is a problem if you ever clear your browser data, especially with the web extensions that need to be disabled for full functionality of this repo, such as Comfy.EditAttention, that you may not remember the names of.  It's particularly problematic if you don't save browser data between sessions, or regularly clean it out, making it tedious to set up your settings again every time.

If settings could be migrated from browser data to ComfyUI's comfy.settings.json file instead, that would be much appreciated.  While we're at it, it would also be nice if the image drawer's default height, width, and column count could be added to the settings modal like the anchor is, so that they could be loaded from json as well.

**Comment by JaredTherriault** [comment]
Hey, thanks for this recommendation. I went ahead and moved all settings over to comfy.settings with localStorage as a backup.  Go ahead and pull latest.

**Comment by Monty1836** [comment]
Thanks, looks like it's working correctly on my end.  It's definitely appreciated.
