### ISSUE TITLE
Right clicking image in lightbox closes it.

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#9]
Not a particularly serious issue, given that right clicking the image in the feed gives the same options, but still a minor one.

I like the addition of dragging, and zooming the image compared to the original image feed by pysssss, but I have built up the habit of opening images in a new tab by right clicking them in the lightbox.  That unfortunately has some slight issues here.

When you right click the image in the lightbox, instead of opening the context menu, it acts the same as a left click.  That means right clicking will close the lightbox, and a right click, and drag will drag around the image, but does open the context menu after.

**Comment by JaredTherriault** [comment]
Thanks for the suggestion! This should be implemented now, give it a try!

**Comment by Monty1836** [comment]
Thanks!  Right click can still drag the image around, but doesn't close the lightbox anymore.  I don't think it hurts anything though, and someone might like it, so I don't see a reason to change it.
